name: Create Forwarder Binary

on:
  push:
    branches:
        - master
        - release-candidate
        - release

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Forwarder
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create Directory
        run: sudo mkdir -p /var/haltdos/forwarder

      - name: Install Dependencies
        run: pip install .[dev]

      - name: Building Forwarder Binary
        run: python -u release/build.py standalone-binaries
  
      - name: Checkout Devops Script Repo
        uses: actions/checkout@v2
        with:
          repository: 'halt-dos/devops-scripts'
          path: devops-scripts
    
      - name: Make Python script executable
        run: chmod +x devops-scripts/upload.py

      - name: Make script executable
        run: chmod +x build.sh
  
      - name: Fetch UAT Version
        id: uat-api
        env:
          USERNAME: ${{ secrets.UAT_API_USERNAME }}
          PASSWORD: ${{ secrets.UAT_API_PASSWORD }}
          COMPONENT_ID: ${{ secrets.UAT_COMPONENT_ID }}
        run: |
          uat_version=$(curl -s -k -u "$USERNAME:$PASSWORD" https://license-uat.hltdos.com/api/component/$COMPONENT_ID/versions | jq '.data[-1].context.version')
          uat_version=`expr $uat_version + 1`
          echo "::set-output name=uat_version::$uat_version"
  
      - name: Build for UAT
        env:
          UAT: ${{ steps.uat-api.outputs.uat_version }}
        run: |
          sudo ./build.sh -p $UAT
          uat_hash=$(sha512sum forwarder-v$UAT.tar.gz)
          cp forwarder-v$UAT.tar.gz /tmp/
          echo "::set-output name=uat_hash::$uat_hash"
  
      - name: Push to UAT
        env:
          UAT_API_USERNAME: ${{ secrets.UAT_API_USERNAME }}
          UAT_API_PASSWORD: ${{ secrets.UAT_API_PASSWORD }}
          UAT_COMPONENT_ID: ${{ secrets.UAT_COMPONENT_ID }}
          UAT: ${{ steps.uat-api.outputs.uat_version }}
        run: |
          devops-scripts/upload.py /tmp/forwarder-v$UAT.tar.gz $UAT UAT ${GITHUB_REF##*/}

    # - name: Fetch PROD Version
    #   id: prod-api
    #   env:
    #     USERNAME: ${{ secrets.PROD_API_USERNAME }}
    #     PASSWORD: ${{ secrets.PROD_API_PASSWORD }}
    #     COMPONENT_ID: ${{ secrets.PROD_COMPONENT_ID }}
    #   run: |
    #     prod_version=$(curl -s -k -u "$USERNAME:$PASSWORD" https://license.haltdos.com/api/component/$COMPONENT_ID/versions | jq '.data[-1].context.version')
    #     prod_version=`expr $prod_version + 1`
    #     echo "::set-output name=prod_version::$prod_version"

    # - name: Build for PROD
    #   env:
    #     PROD: ${{ steps.prod-api.outputs.prod_version }}
    #   run: |
    #     sudo ./build.sh -p $PROD
    #     prod_hash=$(sha512sum forwarder-v$PROD.tar.gz)
    #     cp forwarder-v$PROD.tar.gz /tmp/
    #     echo "::set-output name=prod_hash::$prod_hash"

    # - name: Push to PROD
    #   env:
    #     PROD_API_USERNAME: ${{ secrets.PROD_API_USERNAME }}
    #     PROD_API_PASSWORD: ${{ secrets.PROD_API_PASSWORD }}
    #     PROD_COMPONENT_ID: ${{ secrets.PROD_COMPONENT_ID }}
    #     PROD: ${{ steps.prod-api.outputs.prod_version }}
    #   run: |
    #     devops-scripts/upload.py /tmp/forwarder-v$PROD.tar.gz $PROD PROD ${GITHUB_REF##*/}